name: Webify & Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Webify
        uses: webifier/build@master
        with:
          baseurl: ''
          index: index/index.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          allow_empty_commit: true
          publish_dir: ./webified/
          exclude_assets: '.github,templates,LICENSE'
